version: "3.9"
services:
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
  app:
    image: dotnetapp
    ports:
      - "17644:80"
    restart: on-failure
    depends_on:
      - rabbit
  generator:
    image: generator
    restart: on-failure
    depends_on:
      - rabbit