version: "3.9"
services:
  rabbit:
    image: rabbitmq:3-alpine
  app:
    image: dotnetapp
    ports:
      - "17644:80"
    restart: on-failure
    depends_on:
      - rabbit
  generator:
    image: generator
    restart: on-failure
    depends_on:
      - rabbit