  si_176446_rabbit:
    image: rabbitmq:3-alpine
  si_176446_app:
    image: yaltuzz/si_176446_dotnet
    ports:
      - "17645:80"
    restart: on-failure
    depends_on:
      - si_176446_rabbit
  si_176446_generator:
    image: yaltuzz/si_176446_generator
    restart: on-failure
    depends_on:
      - si_176446_rabbit
  si_176446_front:
    image: yaltuzz/si_176446_front
    ports:
      - "17644:8080"
    restart: on-failure